### ISSUE TITLE
Keeping the items selected when moving

### ISSUE THREAD

**Issue by craskul** [esausilva/jquery.selectlistactions.js#2]
Is there a way to keep the items selected so that when they get submitted in the form, they actually get passed using regular html POST form code?

Basically when the jQuery code selects my choice and copies it to list2, I'd like it to copy this
`<option value="Anesthesiology"> Anesthesiology </option>`

but write this in the second list

`<option value="Anesthesiology" selected> Anesthesiology </option>`

**Comment by esausilva** [comment]
You can do something like this.

See the loop

```js
  $.fn.moveToList = function(sourceList, destinationList) {
    var opts = $(sourceList + ' option:selected');
    if (opts.length == 0) {
      alert("Nothing to move");
    }
    
    for (var i = 0; i < opts.length; i++) {
        opts[i].setAttribute("selected","selected");
    }

    $(destinationList).append($(opts).clone());
  };

```
